name: example
on:
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: Java ${{matrix.Java}} and ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        java: [ '8', '11', '17' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{matrix.java}}
      - run: mvn test
